//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _WIRELESSDATACOLLECTOR_SENSING_H_
#define _WIRELESSDATACOLLECTOR_SENSING_H_

#include <TinyCLR_Interop.h>
struct Library_WirelessDataCollector_Sensing_Samraksh_AppNote_Program
{
    static const int FIELD_STATIC__ApplicationIdSize = 0;
    static const int FIELD_STATIC___applicationIdBytes = 1;
    static const int FIELD_STATIC__MessageTypeSize = 2;
    static const int FIELD_STATIC__MessageTypePos = 3;
    static const int FIELD_STATIC__MessageSequencePos = 4;
    static const int FIELD_STATIC__MessageTimePos = 5;
    static const int FIELD_STATIC__PayloadHeaderSize = 6;
    static const int FIELD_STATIC__HelloTimer = 7;
    static const int FIELD_STATIC__SensingTimer = 8;
    static const int FIELD_STATIC___csmaRadio = 9;
    static const int FIELD_STATIC___lcd = 10;
    static const int FIELD_STATIC___baseStationId = 11;
    static const int FIELD_STATIC___messageSequence = 12;
    static const int FIELD_STATIC__MessageTimers = 13;
    static const int FIELD_STATIC___currState = 14;
    static const int FIELD_STATIC__SensorSurrogate = 15;


    //--//

};

struct Library_WirelessDataCollector_Sensing_Samraksh_AppNote_Program__MessageTimer
{
    static const int FIELD__<Sequence>k__BackingField = 1;
    static const int FIELD__<SeqTimer>k__BackingField = 2;
    static const int FIELD__<StartTime>k__BackingField = 3;


    //--//

};

struct Library_WirelessDataCollector_Sensing_Samraksh_AppNote_Utility_SimpleCsmaRadio
{
    static const int FIELD___userReceivedDataCallback = 1;
    static const int FIELD___csma = 2;


    //--//

};

struct Library_WirelessDataCollector_Sensing_Samraksh_AppNote_Resources
{
    static const int FIELD_STATIC__manager = 16;


    //--//

};

struct Library_WirelessDataCollector_Sensing_Samraksh_AppNote_Utility_BitConverter
{
    static const int FIELD_STATIC__IsLittleEndian = 17;


    //--//

};

struct Library_WirelessDataCollector_Sensing_Samraksh_AppNote_Utility_SimpleTimer
{
    static const int FIELD__TheTimer = 1;
    static const int FIELD___timerCallback = 2;
    static const int FIELD___callBackValue = 3;
    static const int FIELD___initialDueTime = 4;
    static const int FIELD___initialPeriod = 5;
    static const int FIELD___currDueTime = 6;
    static const int FIELD___currPeriod = 7;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_WirelessDataCollector-Sensing;

#endif  //_WIRELESSDATACOLLECTOR_SENSING_H_
