//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _REALTIMETIMER_H_
#define _REALTIMETIMER_H_

#include <TinyCLR_Interop.h>
struct Library_RealTimeTimer_Samraksh_SPOT_RealTime_Timer
{
    TINYCLR_NATIVE_DECLARE(Dispose___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(Change___STATIC__BOOLEAN__U4__U4);
    TINYCLR_NATIVE_DECLARE(GenerateInterrupt___STATIC__VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_RealTime;

#endif  //_REALTIMETIMER_H_
