@echo OFF
set PATH=%WINDIR%\Microsoft.NET\Framework\v4.0.30319;%CD%;%PATH%
SET SPOCLIENT=%CD%
SET SPOROOT=%CD%
SET CLRROOT=%CD%
set BUILD_ROOT_BASE=%CD%
set BUILD_TREE_SERVER=%CD%
set DEVPATH=%BUILD_TREE_SERVER%\dll
set FLAVOR_DAT=Debug
set FLAVOR_WIN=Debug

if "%COMMON_BUILD_ROOT%"=="" set COMMON_BUILD_ROOT=%CLRROOT%
set BUILD_ROOT_BASE=%COMMON_BUILD_ROOT%\BuildOutput

IF "%COVERAGEBUILDID%" == "" (
	set BUILD_ROOT=%BUILD_ROOT_BASE%\public
) ELSE (
	set BUILD_ROOT=%BUILD_ROOT%\Coverage
)

set BUILD_TREE=%BUILD_ROOT%\%FLAVOR_DAT%
set BUILD_TREE_CLIENT=%BUILD_TREE%\client
set BUILD_TREE_SERVER=%BUILD_ROOT%\%FLAVOR_WIN%\server
set DEVPATH=%BUILD_TREE_SERVER%\dll

echo Done