//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "RealTimeTimer.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_RealTimeTimer_Samraksh_SPOT_RealTime_Timer::Dispose___STATIC__VOID,
    Library_RealTimeTimer_Samraksh_SPOT_RealTime_Timer::Change___STATIC__BOOLEAN__U4__U4,
    Library_RealTimeTimer_Samraksh_SPOT_RealTime_Timer::GenerateInterrupt___STATIC__VOID,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_SPOT_RealTime =
{
    "Samraksh_SPOT_RealTime", 
    0x25274F8E,
    method_lookup
};

